export const datas = [
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "AIR",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "FCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "AIR",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "FCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
  ];